#!/usr/bin/env python3
"""
Stop hook — writes a session log entry and reminds Claude to suggest /capture or /preserve.

Registered in: C:\Users\bradh\.claude\settings.json (global)
Triggers on:   Every session end (Stop event)
Only acts on:  Known project directories
"""

import json
import sys
import os
from pathlib import Path
from datetime import datetime

VAULT = Path(r"D:\Claude Repo\Claude Skills Vault")
LOGS_DIR = VAULT / "CC-Session-Logs"

# Map path substrings to project names and their capture command
PROJECTS = {
    "SharePoint Uplift": ("SharePoint Uplift", "capture"),
    "Claude Skills Vault": ("Claude Skills Vault", "preserve"),
    "antigravity-awesome-skills": ("Antigravity Skills", None),  # reference only
}


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        sys.exit(0)

    cwd = data.get("cwd") or os.getcwd()
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    date_str = datetime.now().strftime("%d-%m-%Y")
    time_str = datetime.now().strftime("%H_%M")

    # Identify which project this session was in
    matched_project = None
    matched_command = None
    for path_key, (project_name, command) in PROJECTS.items():
        if path_key.lower() in cwd.lower():
            matched_project = project_name
            matched_command = command
            break

    if not matched_project:
        sys.exit(0)  # Not a tracked project — do nothing

    # Write session log entry
    LOGS_DIR.mkdir(exist_ok=True)
    log_file = LOGS_DIR / f"{date_str}-{time_str}-{matched_project.lower().replace(' ', '-')}.md"

    log_content = f"""---
project: {matched_project}
session-end: {timestamp}
cwd: {cwd}
---

# Session Log — {matched_project} ({timestamp})

_Auto-generated by hook_session_log.py at session end._

Review this file and run `/{matched_command or 'capture'}` in the next session to preserve key context.
"""

    log_file.write_text(log_content, encoding="utf-8")

    # Return reminder to Claude via stdout (appears in Claude's context)
    reminder = f"[hook:session] Session ended in project: {matched_project}."
    if matched_command == "preserve":
        reminder += " Run /preserve to update CLAUDE.md with key learnings."
    elif matched_command == "capture":
        reminder += " Run /capture to save key decisions and status to the Projects/ note."

    print(reminder)


if __name__ == "__main__":
    main()
